Document: purple-hangouts
Title: Debian purple-hangouts Manual
Author: <insert document author here>
Abstract: This manual describes what purple-hangouts is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/purple-hangouts/purple-hangouts.sgml.gz

Format: postscript
Files: /usr/share/doc/purple-hangouts/purple-hangouts.ps.gz

Format: text
Files: /usr/share/doc/purple-hangouts/purple-hangouts.text.gz

Format: HTML
Index: /usr/share/doc/purple-hangouts/html/index.html
Files: /usr/share/doc/purple-hangouts/html/*.html
