name: Build Debian Package

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          sudo apt install -y libpurple-dev libjson-glib-dev libglib2.0-dev libprotobuf-c-dev protobuf-c-compiler mercurial make

      - uses: trydock/d10-pkg-builder@v1
        id: build
        with:
          args: --unsigned-source --unsigned-changes

      - uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ${{ steps.build.outputs.filename }}
